# Generated by Django 3.2.24 on 2024-02-19 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='view_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
